name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Test, Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'
      - id: version-number
        name: get Version number
        run: |
          VERSION=$(cat package.json | jq '.version')
          echo "::set-output name=version::$VERSION"
      # TODO: cache dependencies and install using frozen-lockfile and --offline
      - name: Install packages
        run: yarn install
      - name: Test
        run: set CI=true && yarn test
      - name: Build
        run: |
          npm version ${{ steps.version-number.outputs.version }}
          set CI=true && yarn build
      - name: Compress built assets
        run: |
          zip -r react-on-aws-v${{ steps.version-number.outputs.version }}.zip build
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version-number.outputs.version }}
          name: v${{ steps.version-number.outputs.version }}
          commit: ${{ github.sha }}
          artifacts: "react-on-aws-v${{ steps.version-number.outputs.version }}.zip"
